
package Interface;

import gamefestival.Colaborador;
import gamefestival.ColaboradorPago;
import gamefestival.ColaboradorVoluntario;
import gamefestival.GameFestival;
import gamefestival.ListaColaboradores;
import static java.awt.Color.WHITE;
import java.awt.Toolkit;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class ColaboradorVoluntarioRegisto extends javax.swing.JFrame {
    private GameFestival game;
    private ImprimeColaboradores listagem;
    private Colaborador colaborador;
    
    

    /**
     * Creates new form ColoboradoresVoluntarios
     */
    public ColaboradorVoluntarioRegisto(GameFestival game, Colaborador colaborador, ImprimeColaboradores listagem) {
        initComponents();
        setICon();
        this.game = game;
        this.colaborador = colaborador;
        this.listagem = listagem;
         getContentPane().setBackground(WHITE);
       
        if (registoNovo()) {    
            //Altera o titulo da janela
            //Como construimos sempre uma nova janela, as caixas de texto já estão limpas
            setTitle("Criação de novo Colaborador");
            nomeCV.requestFocus();                      
        }else{
            //No caso de um registo existente
            //Altera o titulo da janela
            setTitle("Alteração de dados de Colaborador");
            //Preenche as caixas de texto com os dados do utilizador
            nomeCV.setText(colaborador.getNome());
            moradaCV.setText(colaborador.getMorada());            
            funcaoCV.setText(colaborador.getFuncao());
            numTelCV.setText(colaborador.getNumTel());
           
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeCV = new javax.swing.JTextField();
        moradaCV = new javax.swing.JTextField();
        funcaoCV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        numTelCV = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Registar Novo Colaborador Voluntário");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar Colaborador Voluntário");
        setForeground(java.awt.Color.white);
        setResizable(false);

        jLabel2.setText("Nome:");

        jLabel3.setText("Morada:");

        jLabel4.setText("Num. Tel. :");

        jLabel5.setText("Função:");

        funcaoCV.setMinimumSize(new java.awt.Dimension(14, 22));

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(funcaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numTelCV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCV, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moradaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeCV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moradaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTelCV, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(funcaoCV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        submeter();
        listagem.atualizar();
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean registoNovo() {
        //Se utililizador == null consideramos que é um novo registo
        return colaborador == null;
    }    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField funcaoCV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField moradaCV;
    private javax.swing.JTextField nomeCV;
    private javax.swing.JTextField numTelCV;
    // End of variables declaration//GEN-END:variables
 
    private void setICon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconImage_1.png")));
    }

    private void submeter(){
        if (registoNovo()){
       if(nomeCV.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Introduza o seu Nome!");            
            nomeCV.requestFocus();
            return;
    }
    
        if (!(Pattern.matches("^[a-zA-Z_ ]+$", nomeCV.getText()))) {
            JOptionPane.showMessageDialog(null, "Por favor introduza um nome válido");
            nomeCV.requestFocus();
            return;
}
    if(moradaCV.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Introduza uma Morada!");            
            moradaCV.requestFocus();
            return;
    }
    if(numTelCV.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Introduza um numero de Telemovel!");            
            numTelCV.requestFocus();
            return;
    }
    if (!(Pattern.matches("^[0-9 +]+$", numTelCV.getText()))) {
    JOptionPane.showMessageDialog(null, "Por favor introduza um numero de telemóvel válido");
           numTelCV.requestFocus();
            return;
    }
    if(funcaoCV.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Introduza uma Funcao!");            
            funcaoCV.requestFocus();
            return;
    }
        
        
        String nome = nomeCV.getText();
        String morada = moradaCV.getText();
        String numTel = numTelCV.getText();
        String funcao = funcaoCV.getText();
        
       ColaboradorVoluntario colv = new ColaboradorVoluntario();
       colv.setNome(nome);
       colv.setMorada(morada);
       colv.setNumTel(numTel);
       colv.setFuncao(funcao);
  
        
       
        game.adicionarColaborador(colv);
        
        dispose();
   
    }else{
         if (!(Pattern.matches("^[a-zA-Z_ ]+$", nomeCV.getText()))) {
            JOptionPane.showMessageDialog(null, "Por favor introduza um nome válido");
            nomeCV.requestFocus();
            return;
}
    if(moradaCV.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Introduza uma Morada!");            
            moradaCV.requestFocus();
            return;
    }
    if(numTelCV.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Introduza um numero de Telemovel!");            
            numTelCV.requestFocus();
            return;
    }
    if (!(Pattern.matches("^[0-9 +]+$", numTelCV.getText()))) {
    JOptionPane.showMessageDialog(null, "Por favor introduza um numero de telemóvel válido");
           numTelCV.requestFocus();
            return;
    }
    if(funcaoCV.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Introduza uma Funcao!");            
            funcaoCV.requestFocus();
            return;
    }

    
    
        
   
        

       colaborador.setNome(nomeCV.getText());
       colaborador.setMorada(moradaCV.getText());
       colaborador.setNumTel(numTelCV.getText());
       colaborador.setFuncao(funcaoCV.getText());
 
        
        dispose();
    }
}
}
    



