/*
 * Copyright (C) 2017 vhoa1
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Interface;

import gamefestival.GameFestival;
import gamefestival.Patrocinio;
import static java.awt.Color.WHITE;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author vhoa1
 */
public class ImprimePatrocinios extends javax.swing.JFrame {
private AbstractTableModel modeloTabela;
private GameFestival game;

    /**
     * Creates new form ImprimeGameDesigners
     */
    public ImprimePatrocinios(GameFestival game) {
        initComponents();
        this.game = game;
        setICon();
        this.modeloTabela = criarModeloTabela();
        tabPatrocinios.setModel(modeloTabela);
        JScrollPane enclosingScrollPane = (JScrollPane) tabPatrocinios.getParent().getParent();
        enclosingScrollPane.setBorder(BorderFactory.createEmptyBorder());
        getContentPane().setBackground(WHITE);
        TotalP.setText(Integer.toString(game.getListaPatrocinios().size()));
        SalarioPT.setText(Float.toString(game.getListaPatrocinios().salarioTotalPatrocinioss()));
    }
    
    private void editar() {
        int rowIndex = tabPatrocinios.getSelectedRow();
        //Se nenhum registo selecionado, nao é possivel editar
        if (rowIndex == -1) return;
        
        String Nome = (String) modeloTabela.getValueAt(rowIndex, 0);
        
        
   
        gamefestival.Patrocinio patrocinio = game.getListaPatrocinios().getPatrocinio(tabPatrocinios.getSelectedRow());
          game.getListaPatrocinios().getPatrocinio(tabPatrocinios.getSelectedRow());
             Patrocinador janela = new Patrocinador(game, patrocinio, this);
          janela.setVisible(true);
       
      
    }
    
    
    
    
    
    private AbstractTableModel criarModeloTabela() {   
        String[] nomeColunas = {"Nome", "Contribuição"};
        
        return new AbstractTableModel() {     
            @Override
            public String getColumnName(int column) {
                return nomeColunas[column];
            }
           
            @Override
            public int getRowCount() {
                //Retorna o número de linhas que a tabela deverá ter
                return game.getListaPatrocinios().size();
            }

            @Override
            public int getColumnCount() {
                //Retorna o número de colunas que a tabela deverá ter
                return nomeColunas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
          
                switch (columnIndex) {
                    case 0: 
                        return game.getListaPatrocinios().getPatrocinio(rowIndex).getNome();
                        
                    case 1:
                        return game.getListaPatrocinios().getPatrocinio(rowIndex).getContribuicao();
                    case 2:
                        return game.getListaGameDesigners().getGameDesigner(rowIndex).getNumTel();
                    
                    default:
                        return "";
                }                              
            }            
        };
    }
          
     public void atualizar() {    
        //Informa o modelo que foram efetuadas alteracoes, o modelo informa a tabela e os dados são redesenhados
        modeloTabela.fireTableDataChanged();
    }        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabPatrocinios = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SalarioPT = new javax.swing.JLabel();
        TotalP = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem Patrocínios");

        tabPatrocinios.setBackground(java.awt.Color.white);
        tabPatrocinios.setForeground(java.awt.Color.black);
        tabPatrocinios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabPatrocinios.setFillsViewportHeight(true);
        tabPatrocinios.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabPatrocinios.setSelectionBackground(new java.awt.Color(71, 76, 85));
        tabPatrocinios.setSelectionForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(tabPatrocinios);

        jToggleButton1.setBackground(java.awt.Color.white);
        jToggleButton1.setForeground(java.awt.Color.black);
        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Patrocinios:");

        jLabel2.setText("Receita:");

        SalarioPT.setText("jLabel3");

        TotalP.setText("jLabel3");

        jToggleButton2.setBackground(java.awt.Color.white);
        jToggleButton2.setForeground(java.awt.Color.black);
        jToggleButton2.setText("Editar Patrocínio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalP)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalarioPT))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TotalP)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalarioPT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        dispose();
      
      
      
      
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
     private void setICon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconImage_1.png")));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SalarioPT;
    private javax.swing.JLabel TotalP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jToggleButton2;
    private javax.swing.JTable tabPatrocinios;
    // End of variables declaration//GEN-END:variables
}
