/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import gamefestival.Administrador;
import gamefestival.GameFestival;
import gamefestival.Utilizador;
import gamefestival.serializacao.Serializacao;
import static java.awt.Color.WHITE;
import javax.swing.plaf.*;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class JanelaPrincipal extends javax.swing.JFrame {
    private GameFestival game;
    private Serializacao bd;
   
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal(GameFestival game, Serializacao bd) {
        initComponents();
        setICon();
        this.game = game;
        this.bd = bd;
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        listagens.setVisible(game.getUtilizadorLigado() instanceof Administrador);
        gestao.setVisible(game.getUtilizadorLigado() instanceof Administrador);
        Administrador.setVisible(game.getUtilizadorLigado() instanceof Administrador);
       getContentPane().setBackground(WHITE);
     
    }
         
    
    private void terminar() {        
        if (JOptionPane.showConfirmDialog(null, 
                "Deseja realmente terminar o programa?", 
                "Terminar", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            guardarAlteracoes();
            game.terminar();
             
        }
    }
    private void guardarAlteracoes() {
        bd.guardar(game);
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verCartaz = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        listagens = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        janelaBilhetesVendidos = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        gestao = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        Administrador = new javax.swing.JMenu();
        precoBilhetes = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jCheckBox1.setText("jCheckBox1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");
        jMenu2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Festival");
        setBackground(java.awt.Color.white);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1000, 520));
        setMinimumSize(new java.awt.Dimension(1000, 520));
        setPreferredSize(new java.awt.Dimension(1000, 520));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Software de Gestão do GameFestival");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 459, 34));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 225, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 237, -1, -1));

        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 362, 563, -1));

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/save-128.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 60, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/megamegamega.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 266, 293));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/mario.png"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 202, 275));

        verCartaz.setBackground(java.awt.Color.lightGray);
        verCartaz.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        verCartaz.setForeground(java.awt.Color.black);
        verCartaz.setText("Ver Cartaz");
        verCartaz.setFocusable(false);
        verCartaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCartazActionPerformed(evt);
            }
        });
        getContentPane().add(verCartaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 320, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Pac-Man-Ghost-PNG-Photos.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 630, 140));

        jButton3.setBackground(java.awt.Color.lightGray);
        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setForeground(java.awt.Color.black);
        jButton3.setText("Comprar Bilhete");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 180, 38));

        jMenuBar1.setBackground(java.awt.Color.white);
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        menuRegistos.setBackground(java.awt.Color.white);
        menuRegistos.setForeground(java.awt.Color.black);
        menuRegistos.setText("Registar");

        jMenuItem2.setBackground(java.awt.Color.white);
        jMenuItem2.setForeground(java.awt.Color.black);
        jMenuItem2.setText("Colaborador Pago");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuRegistos.add(jMenuItem2);

        jMenuItem3.setBackground(java.awt.Color.white);
        jMenuItem3.setForeground(java.awt.Color.black);
        jMenuItem3.setText("Colaborador Voluntário");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuRegistos.add(jMenuItem3);

        jMenuItem4.setBackground(java.awt.Color.white);
        jMenuItem4.setForeground(java.awt.Color.black);
        jMenuItem4.setText("Game Designer");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuRegistos.add(jMenuItem4);

        jMenuItem5.setBackground(java.awt.Color.white);
        jMenuItem5.setForeground(java.awt.Color.black);
        jMenuItem5.setText("Patrocinador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuRegistos.add(jMenuItem5);

        jMenuBar1.add(menuRegistos);

        listagens.setBackground(java.awt.Color.white);
        listagens.setForeground(java.awt.Color.black);
        listagens.setText("Listagens");

        jMenuItem1.setBackground(java.awt.Color.white);
        jMenuItem1.setForeground(java.awt.Color.black);
        jMenuItem1.setText("Colaboradores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        listagens.add(jMenuItem1);

        jMenuItem8.setBackground(java.awt.Color.white);
        jMenuItem8.setForeground(java.awt.Color.black);
        jMenuItem8.setText("Patrocinadores");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        listagens.add(jMenuItem8);

        jMenuItem6.setBackground(java.awt.Color.white);
        jMenuItem6.setForeground(java.awt.Color.black);
        jMenuItem6.setText("Game Designers");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        listagens.add(jMenuItem6);

        janelaBilhetesVendidos.setBackground(java.awt.Color.white);
        janelaBilhetesVendidos.setForeground(java.awt.Color.black);
        janelaBilhetesVendidos.setText("Bilhetes Vendidos");
        janelaBilhetesVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janelaBilhetesVendidosActionPerformed(evt);
            }
        });
        listagens.add(janelaBilhetesVendidos);

        jMenuItem11.setBackground(java.awt.Color.white);
        jMenuItem11.setForeground(java.awt.Color.black);
        jMenuItem11.setText("Utilizadores");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        listagens.add(jMenuItem11);

        jMenuBar1.add(listagens);

        gestao.setBackground(java.awt.Color.white);
        gestao.setForeground(java.awt.Color.black);
        gestao.setText("Gestão");

        jMenuItem7.setBackground(java.awt.Color.white);
        jMenuItem7.setForeground(java.awt.Color.black);
        jMenuItem7.setText("Editar Dias");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        gestao.add(jMenuItem7);

        jMenuItem9.setBackground(java.awt.Color.white);
        jMenuItem9.setForeground(java.awt.Color.black);
        jMenuItem9.setText("Informações");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        gestao.add(jMenuItem9);

        jMenuBar1.add(gestao);

        Administrador.setBackground(java.awt.Color.white);
        Administrador.setForeground(java.awt.Color.black);
        Administrador.setText("Administrador");
        Administrador.setToolTipText("");
        Administrador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        precoBilhetes.setBackground(java.awt.Color.white);
        precoBilhetes.setForeground(java.awt.Color.black);
        precoBilhetes.setText("Alterar preço Bilhetes");
        precoBilhetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoBilhetesActionPerformed(evt);
            }
        });
        Administrador.add(precoBilhetes);

        jMenuItem10.setBackground(java.awt.Color.white);
        jMenuItem10.setForeground(java.awt.Color.black);
        jMenuItem10.setText("Alterar Preço Salários");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Administrador.add(jMenuItem10);

        jMenuBar1.add(Administrador);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      
       new ImprimeColaboradores(game).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        ColaboradorPagoRegisto x = new ColaboradorPagoRegisto(game, null, new ImprimeColaboradores(game));
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    
        ColaboradorVoluntarioRegisto x = new ColaboradorVoluntarioRegisto(game, null, new ImprimeColaboradores(game));
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       
        GameDesigners x = new GameDesigners(game, null, new ImprimeGameDesigners(game));
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
     
        Patrocinador x =new Patrocinador(game, null, new ImprimePatrocinios(game));
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
     
       ImprimeGameDesigners x = new ImprimeGameDesigners(game);
       x.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
        new EditarDias(game).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new ImprimePatrocinios(game).setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        terminar();
       
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Lucro x = new Lucro(game);
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void janelaBilhetesVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janelaBilhetesVendidosActionPerformed
        new JanelaBilhetesVendidos(game).setVisible(true);
    }//GEN-LAST:event_janelaBilhetesVendidosActionPerformed

    private void precoBilhetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoBilhetesActionPerformed
        if (game.getAllBilhetes() == 0){
           new PrecoBilhetes(game).setVisible(true);
           
       }else{
            JOptionPane.showMessageDialog(this, "Não é possivel alterar o preço"); 
        }
    }//GEN-LAST:event_precoBilhetesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardarAlteracoes();
        JOptionPane.showMessageDialog(this, "Alterações Guardadas");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verCartazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCartazActionPerformed
        new ImprimeCartaz(game).setVisible(true);
    }//GEN-LAST:event_verCartazActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new SalarioColaborador(game).setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new comprarBilhete(game).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new ListagemUtilizadores(game).setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administrador;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenu gestao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem janelaBilhetesVendidos;
    private javax.swing.JMenu listagens;
    private javax.swing.JMenu menuRegistos;
    private javax.swing.JMenuItem precoBilhetes;
    private javax.swing.JButton verCartaz;
    // End of variables declaration//GEN-END:variables

    private void setICon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconImage_1.png")));
    }

    


}
